# Generated by Django 4.1.2 on 2022-11-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_product_seller_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller_name',
        ),
    ]
