# Generated by Django 4.1.2 on 2022-11-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_product_seller_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('history', models.IntegerField(default=0)),
            ],
        ),
    ]
